export const projectData = [
  {
    name: "Amazon Clone",
    hosted: "https://mayankkatheriya.github.io/Amazon-clone/",
    github: "https://github.com/Mayankkatheriya/Amazon-clone.git",
    type: "CSS",
    img: "./Assets/amazon.gif",
    top: false,
  },
  {
    name: "Animated Login Page",
    hosted:
      "https://mayankkatheriya.github.io/Mini-Project-1-Animated_Login_Page/",
    github:
      "https://github.com/Mayankkatheriya/Mini-Project-1-Animated_Login_Page.git",
    type: "CSS",
    img: "./Assets/login-page.png",
    top: false,
  },
  {
    name: "Landing Page - 1",
    hosted: "https://mayankkatheriya.github.io/Weekly_Test_6-CSS/",
    github: "https://github.com/Mayankkatheriya/Weekly_Test_6-CSS.git",
    type: "CSS",
    img: "./Assets/landing-page-1.png",
    top: false,
  },
  {
    name: "Animation",
    hosted: "https://mayankkatheriya.github.io/Assignment_10-Animations/",
    github: "https://github.com/Mayankkatheriya/Assignment_10-Animations.git",
    type: "CSS",
    img: "./Assets/Animations.png",
    top: false,
  },
  {
    name: "Tailwind Landing Page",
    hosted:
      "https://mayankkatheriya.github.io/Major_Project_using_Tailwind/dist/",
    github:
      "https://github.com/Mayankkatheriya/Major_Project_using_Tailwind.git",
    type: "tailwind",
    img: "./Assets/tailwind-landing-page.png",
    top: false,
  },
  {
    name: "Youtube Clone",
    hosted: "https://mayankkatheriya.github.io/Assignment_8-YouTube_UI/",
    github: "https://github.com/Mayankkatheriya/Assignment_8-YouTube_UI.git",
    type: "CSS",
    img: "./Assets/youtube-clone.png",
    top: false,
  },
  {
    name: "3D Waves",
    hosted: "https://mayankkatheriya.github.io/3D_waves/",
    github: "https://github.com/Mayankkatheriya/3D_waves.git",
    type: "CSS",
    img: "./Assets/3d-waves.png",
    top: false,
  },
  {
    name: "Business landing Page",
    hosted: "https://mayankkatheriya.github.io/Major-Project-CSS/",
    github: "https://github.com/Mayankkatheriya/Major-Project-CSS.git",
    type: "CSS",
    img: "./Assets/business-landing-page.png",
    top: true,
  },
  {
    name: "BookMyShow Clone",
    hosted: "https://mayankkatheriya.github.io/BookMyShow-Clone/",
    github: "https://github.com/Mayankkatheriya/BookMyShow-Clone.git",
    type: "CSS",
    img: "./Assets/BookmyShow.png",
    top: true,
  },
  {
    name: "Photo Gallery CSS",
    hosted: "https://mayankkatheriya.github.io/Photo-gallery_CSS/",
    github: "https://github.com/Mayankkatheriya/Photo-gallery_CSS.git",
    type: "CSS",
    img: "./Assets/photo-gallery.png",
    top: true,
  },
  {
    name: "Light Bulb",
    hosted: "https://mayankkatheriya.github.io/Light_Bulb_JS/",
    github: "https://github.com/Mayankkatheriya/Light_Bulb_JS.git",
    type: "JavaScript",
    img: "./Assets/light_bulb.png",
    top: true,
  },
  {
    name: "Mouse Position",
    hosted: "https://mayankkatheriya.github.io/Weekly_Test-2-Mouse-Event-/",
    github: "https://github.com/Mayankkatheriya/Weekly_Test-2-Mouse-Event-.git",
    type: "JavaScript",
    img: "./Assets/mouse-position.png",
    top: false,
  },
  {
    name: "Change Shape and Color",
    hosted: "https://mayankkatheriya.github.io/Change_Shape_and_Color/",
    github: "https://github.com/Mayankkatheriya/Change_Shape_and_Color.git",
    type: "JavaScript",
    img: "./Assets/chnage_shape_color.png",
    top: false,
  },
  {
    name: "Background Change",
    hosted: "https://mayankkatheriya.github.io/Background_Color_Change/",
    github: "https://github.com/Mayankkatheriya/Background_Color_Change.git",
    type: "JavaScript",
    img: "./Assets/background-change.png",
    top: false,
  },
  {
    name: "Shopping Cart",
    hosted: "https://mayankkatheriya.github.io/Weekly_Test_3_Shopping_Cart/",
    github:
      "https://github.com/Mayankkatheriya/Weekly_Test_3_Shopping_Cart.git",
    type: "JavaScript",
    img: "./Assets/shopping-cart.png",
    top: false,
  },
  {
    name: "Random color Code",
    hosted: "https://mayankkatheriya.github.io/Random_Color-Code/",
    github: "https://github.com/Mayankkatheriya/Random_Color-Code.git",
    type: "JavaScript",
    img: "./Assets/random-color.png",
    top: false,
  },
  {
    name: "Real Time Character Count",
    hosted: "https://mayankkatheriya.github.io/Real_Time_Character_Count/",
    github: "https://github.com/Mayankkatheriya/Real_Time_Character_Count.git",
    type: "JavaScript",
    img: "./Assets/char-count.png",
    top: false,
  },
  {
    name: "Tip Calculator",
    hosted: "https://mayankkatheriya.github.io/Tip_Calculator/",
    github: "https://github.com/Mayankkatheriya/Tip_Calculator.git",
    type: "JavaScript",
    img: "./Assets/tip-calc.png",
    top: false,
  },
  {
    name: "Click Me Game",
    hosted: "https://mayankkatheriya.github.io/Click_me_if_you_can/",
    github: "https://github.com/Mayankkatheriya/Click_me_if_you_can.git",
    type: "JavaScript",
    img: "./Assets/click-me.png",
    top: true,
  },
  {
    name: "Emoji Finder",
    hosted: "https://mayankkatheriya.github.io/Emoji_Project/",
    github: "https://github.com/Mayankkatheriya/Emoji_Project.git",
    type: "JavaScript",
    img: "./Assets/emoji-finder.png",
    top: false,
  },
  {
    name: "Search the Table",
    hosted: "https://mayankkatheriya.github.io/Filter_search_the_table/",
    github: "https://github.com/Mayankkatheriya/Filter_search_the_table.git",
    type: "JavaScript",
    img: "./Assets/search-table.png",
    top: false,
  },
  {
    name: "Sort the Table",
    hosted: "https://mayankkatheriya.github.io/Sort_the_table/",
    github: "https://github.com/Mayankkatheriya/Sort_the_table.git",
    type: "JavaScript",
    img: "./Assets/sort-table.png",
    top: false,
  },
  {
    name: "Login Validation",
    hosted: "https://mayankkatheriya.github.io/Login_Validation/",
    github: "https://github.com/Mayankkatheriya/Login_Validation.git",
    type: "JavaScript",
    img: "./Assets/login-validation.png",
    top: true,
  },
  {
    name: "Digital Clock",
    hosted: "https://mayankkatheriya.github.io/Digital_Clock/",
    github: "https://github.com/Mayankkatheriya/Digital_Clock.git",
    type: "JavaScript",
    img: "./Assets/digital-clock.png",
    top: false,
  },
  {
    name: "BurgerKing Franchise",
    hosted: "https://mayankkatheriya.github.io/BurgerKing_franchise/",
    github: "https://github.com/Mayankkatheriya/BurgerKing_franchise.git",
    type: "JavaScript",
    img: "./Assets/burgerKing.png",
    top: false,
  },
  {
    name: "Dad Jokes Generator",
    hosted: "https://mayankkatheriya.github.io/Dad_Jokes_generator/",
    github: "https://github.com/Mayankkatheriya/Dad_Jokes_generator.git",
    type: "JavaScript",
    img: "./Assets/Dad-Joke.png",
    top: true,
  },
  {
    name: "Phone Hunting API",
    hosted: "https://mayankkatheriya.github.io/Phone_Hunting_API/",
    github: "https://github.com/Mayankkatheriya/Phone_Hunting_API.git",
    type: "JavaScript",
    img: "./Assets/phone_API.png",
    top: false,
  },
  {
    name: "StopWatch",
    hosted: "https://mayankkatheriya.github.io/StopWatch/",
    github: "https://github.com/Mayankkatheriya/StopWatch.git",
    type: "JavaScript",
    img: "./Assets/stopwatch.png",
    top: false,
  },
  {
    name: "Sticky Notes",
    hosted: "https://mayankkatheriya.github.io/Sticky_Notes/",
    github: "https://github.com/Mayankkatheriya/Sticky_Notes.git",
    type: "JavaScript",
    img: "./Assets/sticky.png",
    top: true,
  },
  {
    name: "Payment through Promise",
    hosted: "https://mayankkatheriya.github.io/Google_pay_Payment/",
    github: "https://github.com/Mayankkatheriya/Google_pay_Payment.git",
    type: "JavaScript",
    img: "./Assets/payment-promise.png",
    top: false,
  },
  {
    name: "Image Search",
    hosted: "https://mayankkatheriya.github.io/Image_search/",
    github: "https://github.com/Mayankkatheriya/Image_search.git",
    type: "JavaScript",
    img: "./Assets/image-search.png",
    top: false,
  },
  {
    name: "Github Finder",
    hosted: "https://mayankkatheriya.github.io/Gitthub_finder/",
    github: "https://github.com/Mayankkatheriya/Gitthub_finder.git",
    type: "JavaScript",
    img: "./Assets/github_finder.png",
    top: false,
  },
  {
    name: "Book App",
    hosted: "https://mayankkatheriya.github.io/Book_App/",
    github: "https://github.com/Mayankkatheriya/Book_App.git",
    type: "JavaScript",
    img: "./Assets/Book_app.png",
    top: false,
  },
  {
    name: "Local Storage",
    hosted: "https://mayankkatheriya.github.io/Local_Storage_Project/",
    github: "https://github.com/Mayankkatheriya/Local_Storage_Project.git",
    type: "JavaScript",
    img: "./Assets/local-storage.png",
    top: false,
  },
  {
    name: "Pokemon Project",
    hosted: "https://mayankkatheriya.github.io/Pokemon_project/",
    github: "https://github.com/Mayankkatheriya/Pokemon_project.git",
    type: "JavaScript",
    img: "./Assets/pokemon.png",
    top: true,
  },
  {
    name: "Infinite Scroll",
    hosted: "https://mayankkatheriya.github.io/26-Infinite_Scroll/",
    github: "https://github.com/Mayankkatheriya/26-Infinite_Scroll.git",
    type: "JavaScript",
    img: "./Assets/infinte_scroll.png",
    top: false,
  },
  {
    name: "Movie Search",
    hosted: "https://mayankkatheriya.github.io/25-Movie-Search/",
    github: "https://github.com/Mayankkatheriya/25-Movie-Search.git",
    type: "JavaScript",
    img: "./Assets/movie-search.png",
    top: true,
  },
  {
    name: "JS Libraries",
    hosted: "https://mayankkatheriya.github.io/26-Data_Visualization/",
    github: "https://github.com/Mayankkatheriya/26-Data_Visualization.git",
    type: "JavaScript",
    img: "./Assets/js-library.png",
    top: false,
  },
  {
    name: "Rock Paper Scissors",
    hosted: "https://mayankkatheriya.github.io/Rock_Paper_Scissors/",
    github: "https://github.com/Mayankkatheriya/Rock_Paper_Scissors.git",
    type: "JavaScript",
    img: "./Assets/rock-paper-scissor.png",
    top: false,
  },
  {
    name: "Crypto Search Application",
    hosted: "https://mayankkatheriya.github.io/29-Crypto_Search_Application/",
    github:
      "https://github.com/Mayankkatheriya/29-Crypto_Search_Application.git",
    type: "JavaScript",
    img: "./Assets/crypto-search.png",
    top: true,
  },
  {
    name: "Flipkart Clone",
    hosted: "https://mayankkatheriya.github.io/Flipkart_Clone/",
    github: "https://github.com/Mayankkatheriya/Flipkart_Clone.git",
    type: "JavaScript",
    img: "./Assets/flipkart-clone.png",
    top: true,
  },
  {
    name: "YT Chrome Extension",
    hosted:
      "https://drive.google.com/file/d/1PDAMzIh1VBh7nO3ezObSqJKojPEAm_au/view",
    github: "https://github.com/Mayankkatheriya/Youtube_Chrome_Extension",
    type: "JavaScript",
    img: "./Assets/chromeExtension.gif",
    top: true,
  },
  {
    name: "Text-Utils",
    hosted:
      "https://text-utils-react-gamma.vercel.app/",
    github: "https://github.com/Mayankkatheriya/TextUtils-React.git",
    type: "React",
    img: "./Assets/text-utils.png",
    top: true,
  },
  {
    name: "Password Generator",
    hosted:
      "https://password-generator-three-rho-82.vercel.app/",
    github: "https://github.com/Mayankkatheriya/Password-generator.git",
    type: "React",
    img: "./Assets/password-generator.png",
    top: true,
  },
  {
    name: "Infinite Scroll - React",
    hosted:
      "https://infinite-scroll-react-rho.vercel.app/",
    github: "https://github.com/Mayankkatheriya/Infinite-Scroll-React.git",
    type: "React",
    img: "./Assets/infinte_scroll-react.png",
    top: true,
  },
  {
    name: "Quiz Game",
    hosted:
      "https://quiz-game-orcin-beta.vercel.app/",
    github: "https://github.com/Mayankkatheriya/Quiz-Game.git",
    type: "React",
    img: "./Assets/quiz-game.png",
    top: true,
  },
  {
    name: "MarkDown-Notepad",
    hosted:
      "https://markdown-notepad-mayank.netlify.app/",
    github: "https://github.com/Mayankkatheriya/MarkDown-Notepad.git",
    type: "React",
    img: "./Assets/markdown-notepad.png",
    top: true,
  },
  {
    name: "Grocery Bud",
    hosted:
      "https://to-do-list-sigma-ashen.vercel.app/",
    github: "https://github.com/Mayankkatheriya/TO-Do-List.git",
    type: "React",
    img: "./Assets/grocery-bud.png",
    top: true,
  },
  {
    name: "React-Routing",
    hosted:
      "https://react-routing-mocha.vercel.app/",
    github: "https://github.com/Mayankkatheriya/react-routing.git",
    type: "React",
    img: "./Assets/react-routing.png",
    top: true,
  },
  {
    name: "Budget Planner",
    hosted:
      "https://budget-planner-flame.vercel.app/",
    github: "https://github.com/Mayankkatheriya/Budget-Planner.git",
    type: "React",
    img: "./Assets/budget-planner.png",
    top: true,
  },
  {
    name: "Dice Game",
    hosted:
      "https://dice-game-seven-phi.vercel.app/",
    github: "https://github.com/Mayankkatheriya/Dice-game.git",
    type: "React",
    img: "./Assets/dice-game.png",
    top: true,
  },
  {
    name: "Disney-Clone React",
    hosted:
      "https://disney-clone-psi-henna.vercel.app/",
    github: "https://github.com/Mayankkatheriya/Disney-Clone.git",
    type: "React",
    img: "./Assets/disney+.gif",
    top: true,
  },  
  {
    name: "Login Authentication (Firebase)",
    hosted:
      "https://login-authetication.vercel.app/",
    github: "https://github.com/Mayankkatheriya/Login-Authetication.git",
    type: "React",
    img: "./Assets/login-authentication.png",
    top: true,
  },
  {
    name: "Movie Explorer App",
    hosted:
      "https://movix-app-murex.vercel.app/",
    github: "https://github.com/Mayankkatheriya/Movix-App.git",
    type: "React",
    img: "./Assets/moviesDatabase.gif",
    top: true,
  },
  {
    name: "Cloud Storage Application",
    hosted:
      "https://google-drive-clone-roan.vercel.app/",
    github: "https://github.com/Mayankkatheriya/google-drive-clone.git",
    type: "React",
    img: "./Assets/cloudstorageapp.gif",
    top: true,
  },
  {
    name: "Maching Card Game",
    hosted:
      "https://maching-game-ts.vercel.app/",
    github: "https://github.com/Mayankkatheriya/machingGame_ts.git",
    type: "React",
    img: "./Assets/machinggame.png",
    top: true,
  },
];